FinancieraAcme.PrestaFacil.UI.Web/Controllers/ConsultaProductoAjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using FinancieraAcme.PrestaFacil.UI.Web.Models;

namespace FinancieraAcme.PrestaFacil.UI.Web.Controllers
{
    public class ConsultaProductoAjaxController : Controller
    {
        public async Task<IActionResult> Index()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://financieraacmeapicw101.azurewebsites.net/");
            client.DefaultRequestHeaders.Accept.Clear();
            //Type os MIME that we want to receive (in this case Json)
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            List<Producto> productos = new List<Producto>();

            HttpResponseMessage response =  await client.GetAsync("api/producto");

            if(response.IsSuccessStatusCode)
            {
                productos = await response.Content.ReadAsAsync<List<Producto>>();
            }
            return View(productos);
        }
        public IActionResult Crear()
        {

            return View();
        }

        //[ValidateAntiForgeryToken]//add an hidden field, if petition is by a valid user
        [HttpPost]
        public async Task<IActionResult> Crear([FromBody]  Producto producto)
        {
            //calling directly from Azure,needs to anable CORS in Azure
            //url: "https://financieraacmeapicw101.azurewebsites.net/api/producto",

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://financieraacmeapicw101.azurewebsites.net/");
            client.DefaultRequestHeaders.Accept.Clear();
            //Type os MIME that we want to receive (in this case Json)
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = await client.PostAsJsonAsync("api/producto",producto);
            response.EnsureSuccessStatusCode();

            
            return Json(//creando un documento Json
                new
                {
                    exito = true,
                    mensaje = $"Producto Registrado con exito"
                });
        }
    }

}

FinancieraAcme.PrestaFacil.UI.Web/Controllers/LoanApplicationController.cs
using FinancieraAcme.PrestaFacil.Domain.Entities;
using FinancieraAcme.PrestaFacil.Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinancieraAcme.PrestaFacil.UI.Web.Controllers
{
    public class LoanApplicationController : Controller
    {
        private readonly ILoanApplication _repo;
        //.net core will pass repo internally
        public LoanApplicationController(ILoanApplication repo)
        {
            _repo = repo;
        }
        public IActionResult Index()
        {
            List<LoanApplication> solicitudes = _repo.TraerTodos().ToList();
            //ViewData["Lista"] = solicitudes;
            return View(solicitudes);
        }
        public IActionResult Details(int id)
        {
            LoanApplication loan = _repo.TraerPorId(id);
            if (loan == null)
            {
                return NotFound();//returns 404 by default
            }
            return View(loan);
        }
        public IActionResult Edit(int id)
        {
            LoanApplication loan = _repo.TraerPorId(id);
            if (loan == null)
            {
                return NotFound();
            }
            return View(loan);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(LoanApplication loan)
        {
            if (ModelState.IsValid == false)
            {
                return View(loan);
            }
            _repo.Editar(loan);
            try
            {
                await _repo.GuardarAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (_repo.TraerPorId(loan.Id) == null)
                    return NotFound();
                else
                    throw;
            }
            //otra option
            //ViewData["Mensaje"]="sasa";
            //return View(loan)
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(LoanApplication loan)
        {
            if(ModelState.IsValid==false)
            {
                return View();
            }
            _repo.Agregar(loan);
            await _repo.GuardarAsync();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            LoanApplication loan = _repo.TraerPorId(id);
            if (loan == null)
            {
                return NotFound();
            }
            return View(loan);
        }
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteLoanApplication(int id)
        {

            _repo.Eliminar(id);
            await _repo.GuardarAsync();
            
            return RedirectToAction("Index");
        }
    }
}

FinancieraAcme.PrestaFacil.UI.Web/Controllers/LoanApplicationTxController.cs
using FinancieraAcme.PrestaFacil.Domain.Entities;
using FinancieraAcme.PrestaFacil.Domain.Interfaces;
using FinancieraAcme.PrestaFacil.UI.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinancieraAcme.PrestaFacil.UI.Web.Extensions;

using FinancieraAcme.PrestaFacil.Domain;


namespace FinancieraAcme.PrestaFacil.UI.Web.Controllers
{
    public class LoanApplicationTxController : Controller
    {
        private readonly ILoanApplicationParentRepository _repoMain;
        private readonly IClient _repoClient;
        private readonly IUnitOfWork _ouw;
        //.net core will pass repo internally
        public LoanApplicationTxController(ILoanApplicationParentRepository repoMain,IClient repoClient, IUnitOfWork ouw)
        {
            _repoMain = repoMain;
            _repoClient = repoClient;
            _ouw = ouw;
        }
        public IActionResult EnterApplication()
        {
            LoanApplicationParentViewModel vm = new LoanApplicationParentViewModel(_repoClient.TraerTodos().ToList());
            //vm.Clientes = new List<SelectListItem>(_repoClient.TraerTodos().) 
            //List<LoanApplicationMain> solicitudes = _repoMain.TraerTodos().ToList();
            //ViewData["Lista"] = solicitudes;
            return View(vm);
        }
        [HttpPost]
        public  IActionResult EnterApplication(LoanApplicationParentViewModel vm)
        {

            //will save in a session
            //HttpContext.Session.Set("LoanApplicationMain", vm.LoanApplicationMain)
            HttpContext.Session.Set<LoanApplicationParent>("LoanApplicationParent", vm.LoanApplicationParent);
            var la = HttpContext.Session.Get<LoanApplicationParent>("LoanApplicationParent");

            //Start Deatils List
            HttpContext.Session.Set<List<LoanApplicationChild>>("ListLoanApplicationChild", new List<LoanApplicationChild>());
            ViewBag.Detalles = HttpContext.Session.Get<List<LoanApplicationChild>>("ListLoanApplicationChild");

            //Fill to the next view to fill in Details
            var cliente = _repoClient.TraerPorId(la.ClientId);
            //ViewBag.Client = $"{cliente.Apellidos},{cliente.Nombres} (Id: {cliente.Id})";  //dynamic , all es defined when it is programed
            ViewBag.Client = cliente;
            ViewBag.Date = la.FechaSolicitud.ToLongDateString();

            return View("EnterApplicationDetail");
        }
        [HttpPost]
        public IActionResult EnterApplicationDetail(LoanApplicationChild appDetail)
        {
            List<LoanApplicationChild> details = HttpContext.Session.Get<List<LoanApplicationChild>>("ListLoanApplicationChild");

            details.Add(appDetail);
            HttpContext.Session.Set<List<LoanApplicationChild>>("ListLoanApplicationChild", details);
            ViewBag.Detalles = HttpContext.Session.Get<List<LoanApplicationChild>>("ListLoanApplicationChild");

            var la = HttpContext.Session.Get<LoanApplicationParent>("LoanApplicationParent");
            var cliente = _repoClient.TraerPorId(la.ClientId);
            ViewBag.Client = cliente;
            ViewBag.Date = la.FechaSolicitud.ToLongDateString();
            ModelState.Clear();
            return View();
        }
        public async Task<IActionResult> SaveApplicationDetails()
        {
            LoanApplicationParent main = HttpContext.Session.Get<LoanApplicationParent>("LoanApplicationParent");
            List<LoanApplicationChild> details = HttpContext.Session.Get<List<LoanApplicationChild>>("ListLoanApplicationChild");
;
            
            _ouw.LoanApplicationParentRepository.Agregar(main);
            foreach (var detail in details)
            {
                _ouw.LoanApplicationChildRepository.Agregar(detail);

            }
            await _ouw.GuardarAsync();
            ViewBag.Mensaje = "Saved";
            return View();
        }
    }
}

FinancieraAcme.PrestaFacil.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinancieraAcme.PrestaFacil.UI.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinancieraAcme.PrestaFacil.UI.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoanApplication" asp-action="Index">Loan Application</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoanApplicationSps" asp-action="Index">Loan Application Sps</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ConsultaProductoAjax" asp-action="Index">Consulta Producto Ajax</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoanApplicationTx" asp-action="EnterApplication">Loan Application Tx</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FinancieraAcme.PrestaFacil.UI.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>